### PR TITLE
Change header from bootstrap "container-fluid" to "container"

### LINKED ISSUE #1330: We should ensure header fits within bootstrap's columns
Screen Shot 2024-02-23 at 10 40 52

related to #1319, necessary before we can show a suggested UI update to Debra.

### PR DESCRIPTION
**Pull request by jacobdgm**
This PR updates the header on all pages to be the same width as the main content panel + any sidebars beneath it. This brings the CantusDB logo back from way off on the left, where it used to be. It fixes #1330

This PR also updates many of the templates. Some of these changes were made necessary by then `"container-fluid"`-to-`"container"` change on `base.html`, but others smooth out the formatting of the sidebar (mostly, adding a margin to the bottom of the search bar, which had previously been smooshed up against the sidebar card beneath it). On the chants-by-cantus-ID page, a div with `table-responsive` was necessary to prevent the table from spilling out of the main panel.

In the header, we added a `<br>` to "Docs, Instructions, Tools", thus preventing the header from spilling beyond its white background when between `lg` and `xl` breakpoints (this change also holds when the hamburger menu is expanded).

While working through the templates, I also renamed several of the templates, simplifying and standardizing them (`source_create_form.html`->`source_create.html`, `source_confirm_delete.html`->`source_delete.html`, `chant_confirm_delete.html`->`chant_delete.html`). `urls.py`, several of the views, and `test_views.py` were updated to accommodate these changes.

Much credit goes to @yinanazhou, whose help was invaluable in tracking down which bits of bootstrap needed to be tweaked and in identifying when a solution that went beyond bootstrap was necessary.

### Source Create page
(these screenshots representative of pages that have no cards in the sidebar)
#### before
Screenshot 2024-02-23 at 3 43 30 PM
#### after
Screenshot 2024-02-23 at 3 44 38 PM

### My Sources page
(these screenshots representative of pages that have only a single card in the sidebar)
#### before
Screenshot 2024-02-23 at 3 22 58 PM
#### after
Screenshot 2024-02-23 at 3 22 00 PM

### Chant Detail page
(these screenshots representative of other pages that have two cards in the sidebar)
#### before
Screenshot 2024-02-23 at 3 37 33 PM
#### after
Screenshot 2024-02-23 at 3 38 42 PM

### Source Detail page
(these screenshots representative of other pages that have three cards in the sidebar)
#### before
Screenshot 2024-02-23 at 3 46 46 PM
#### after
Screenshot 2024-02-23 at 3 47 21 PM

(these screenshots representative of the other pages at narrow breakpoints)
#### before, narrow breakpoint
Screenshot 2024-02-23 at 3 33 46 PM
#### after, narrow breakpoint
Screenshot 2024-02-23 at 3 33 07 PM

#### before
Screenshot 2024-02-23 at 3 51 44 PM
#### after
Screenshot 2024-02-23 at 3 51 53 PM

### CODE REVIEW

**Review by yinanazhou — APPROVED** [review]
Looks good :)

**Comment by jacobdgm** [comment]
Going to hold off on merging until we've deployed the updated concordances API (#1323) to the Staging server.

**Comment by jacobdgm** [comment]
marking as a draft for now so no one accidentally merges it in the next couple of days.

**Comment by jacobdgm** [comment]
oops! - having pushed these changes to Staging, I see that the articles pages and the flatpages have not been made to look like the pages in the screenshot. Must fix before this goes to production!

**Pull request merged**
