### PR TITLE
Merge staging into production, 14 Aug 2024

### PR DESCRIPTION
**Pull request by lucasmarchd01**
_Global Changes_
- [x] Update URLs, models, codebase, and admin pages to use "service" instead of "office" by @lucasmarchd01 in https://github.com/DDMAL/CantusDB/pull/1582
- [x] Partial database back-up for RISM is created (#1614)

_Source/Institution Identification_

This was implemented in many PRs (#1545, #1566, #1568, #1570, #1584, #1586, #1645, #1615, #1606, #1629, #1618). There are many conversations and emails for all of the different pieces of this transition (too many to really summarize here). However, the key points are:
- [x] `Source`, `SourceIdentifier`, `Institution`, and `InstitutionIdentifier` migrations run correctly
- [x] `migrate_records` command runs correctly on
    - [x] regular sources
    - [x] printed sources
    - [x] private collections
    - [x] virtual reconstructions
    - [x] fragments
- [x] Source List page looks good for:
    - [x] regular sources
    - [x] printed sources
    - [x] private collections
    - [x] virtual reconstructions
    - [x] fragments
    - [x] sources with colloquial names
- [x] Source Create/Edit pages look good for:
    - [x] regular sources
    - [x] printed sources
    - [x] private collections
    - [x] virtual reconstructions
    - [x] fragments
    - [x] sources with colloquial names
- [x] Source Detail pages look good for:
    - [x] regular sources
    - [x] printed sources
    - [x] private collections
    - [x] virtual reconstructions
    - [x] fragments
    - [x] sources with colloquial names
- [x] Norway-based sources migrate correctly (#1666)
- [x] Admin pages looks good for sources
- [x] Institution views (detail and list) look good
    - [x] Pages for no city/country look good (#1666)
    - [x] Bower segment named correctly (#1666)
    - [x] Colloquial names of sources show alongside sigla (#1666)

_Frontend/Templates_
- [x] Change links under Resources menu and add link to procedures manual by @dchiller in https://github.com/DDMAL/CantusDB/pull/1557
- [x] Add legacy logos for acknowledgements page by @lucasmarchd01 in https://github.com/DDMAL/CantusDB/pull/1574
- [x] Change instances of "Differentia Database" to "Differentiae Database" by @lucasmarchd01 in https://github.com/DDMAL/CantusDB/pull/1575

_Source Views_
- [x] Change help text for `date` field in `Source` model. Black formatting changes by @lucasmarchd01 in https://github.com/DDMAL/CantusDB/pull/1567
- [x] Change help text for `date` field on source edit page by @lucasmarchd01 in https://github.com/DDMAL/CantusDB/pull/1603
- [x] Add many-to-many segment field to source model by @dchiller in https://github.com/DDMAL/CantusDB/pull/1577
- [x] Add country and source columns to browse sources table by @dchiller in https://github.com/DDMAL/CantusDB/pull/1578
- [x] Add country filter to source list page (#1605) (DH: Checking this off b/c it works; making new issue #1664 for the fact that there are some "phantom" countries for unauthenticated users)
- [x] "Search melodies in this source" works (#1648)
- [x] `source_completeness` field options display as "Complete Source", "Fragment", "Reconstruction" and `complete_inventory` field options display as "Full inventory" and "partial inventory" (#1666)
- [x] Source completeness filter works correctly (#1666)
- [x] All source centuries show correctly, if multiple exist (#1669)

_Chant Views_
- [x] Escape special characters in suggested chant data by @lucasmarchd01 in https://github.com/DDMAL/CantusDB/pull/1561
- [x] Chant create: optimize suggested chants feature by @dchiller in https://github.com/DDMAL/CantusDB/pull/1579
- [x] Improper characters don't break Chant Create, Chant Edit, Chant Detail, Chant Edit Syllabification views (#1653)
- [x] Display additional chant fields on Chant Detail page when they exist by @dchiller in https://github.com/DDMAL/CantusDB/pull/1573
- [x] Volpiano is not displayed for MS 073 (#1649)
- [x] Display chant.project on Chant Detail page where it exists (#1621)

_Chant Search_
- [x] Add indexing notes search to chant search page by @lucasmarchd01 in https://github.com/DDMAL/CantusDB/pull/1576

_Commands_
- [x] Add command to reassign feast data and update chants by @lucasmarchd01 in https://github.com/DDMAL/CantusDB/pull/1564
- [x] `remap_user_ids` works (#1662)
- [x] `map_cantus_ids` works (#1662)
- [x] `reformat_source_ids` works  (#1651)
- [x] `populate_source_completeness` works (#1645)
    - [x] Sources with `full_source = None` map to `source_completeness = "Complete Source"` (#1666)

_APIs_
- [x] ~~`json-cid` endpoint works with 909000 (#1656)~~ (DH: Reopened #1655)
- [x] Maintain backwards compatibility with APIs (#1643)
- [x] Working JSON endpoint for `Service` and `Genre` list and detail views (#1612)

_Admin_
- [x] Fix `FieldError` on admin user change page (#1600)

_Code cleanliness/refactoring_
- [x] Put view classes in separate files by @dchiller in https://github.com/DDMAL/CantusDB/pull/1563
- [x] Refactor `test_views` to match separate view class files (various)

Commands to run on production (copying from #1663):
0. Run migrations
1. Run reformat_source_ids (Formats DACT and Fragment ID fields; run before migrate_records so that these are correctly formatted when used in the shelfmark field).
2. Run migrate_records.
3. Run other commands that needed testing:
    - remap_user_ids
    - map_cantus_ids "008248:24" "008248:08"
    - combining feasts command for 2456 -> 4474 and 2094 -> 4475
    - run populate_diff_id_fields
    - run populate_source_completeness command

Two sources (699079 and 698806) have been "pre-migrated" and will need manual attention when production is updated.

Printed sources will need manual attention after updating:
- any institution changes (email conversations have suggested we want to reference a particular copy in some cases)
- population the `production_method` field

### CODE REVIEW

**Comment by dchiller** [comment]
Thanks @lucasmarchd01 ! I'll start testing.

**Comment by lucasmarchd01** [comment]
Has the command to reassign feasts in #1564 already been run? I noticed they've already been reassigned and deleted before I ran the command.

Also, I'm just about to run #1580

**Comment by dchiller** [comment]
> Has the command to reassign feasts in #1564 already been run? I noticed they've already been reassigned and deleted before I ran the command.

Hmm...I don't think I ran it. At least, I shouldn't have. 

> Also, I'm just about to run #1580

Nice! 🤞

**Comment by dchiller** [comment]
> Has the command to reassign feasts in #1564 already been run? I noticed they've already been reassigned and deleted before I ran the command.

Wait it looks like you ran it: https://github.com/DDMAL/CantusDB/issues/1560#issuecomment-2269241101

😉

**Comment by lucasmarchd01** [comment]
> Wait it looks like you ran it: [#1560 (comment)](https://github.com/DDMAL/CantusDB/issues/1560#issuecomment-2269241101)
> 
> 😉

🤦‍♂️

**Comment by dchiller** [comment]
Ok, because these changes do a bunch with the sources and institutions, I'm gonna email everyone to take a look too. For example, at this page: https://staging.cantusdatabase.org/sources/. 

I know that Debra also wanted #1583, but that could come in a future release.

**Comment by lucasmarchd01** [comment]
> Ok, because these changes do a bunch with the sources and institutions, I'm gonna email everyone to take a look too. For example, at this page: https://staging.cantusdatabase.org/sources/.

Good idea!

> I know that Debra also wanted https://github.com/DDMAL/CantusDB/issues/1583, but that could come in a future release.

We can also try and quickly push this feature to staging. I assumed we'd have to do another merge of develop into staging before the release anyways.

**Comment by dchiller** [comment]
@lucasmarchd01 I am getting a 404 on flatpages on staging...are you?

**Comment by lucasmarchd01** [comment]
> @lucasmarchd01 I am getting a 404 on flatpages on staging...are you?

Interesting... I can access the flatpages when I'm logged out, but once I log in I'm getting the 404.

**Comment by dchiller** [comment]
> Interesting... I can access the flatpages when I'm logged out, but once I log in I'm getting the 404.

Ah ok, I didn't realize it but that's exactly what's happening with me too. 

Update: also doesn't happen to me on develop locally. 

Update 2: I just found #1608 on staging, but I'm not sure that that would be relevant to this problem.

Update 3: I believe this has been solved. See #1610.

**Comment by lucasmarchd01** [comment]
Are we ready to merge into production?

**Comment by dchiller** [comment]
@lucasmarchd01 Ok, imho this is ready to go... thoughts?

**Comment by lucasmarchd01** [comment]
Sounds good to me. Exciting that we're finally getting these changes up, thanks for all your hard work!

**Comment by dchiller** [comment]
Thank you! And thanks @ahankinson! I'll start shortly.

**Review by dchiller — APPROVED** [review]

**Pull request merged**
