### PR TITLE
Prepare repo for use of ansible deployment

### PR DESCRIPTION
**Pull request by dchiller**
This PR makes changes to the repository so that we can use ansible for deployment. See the [CantusDB ansible repo](https://github.com/dact-chant/ansible.cantus-db) for details on that deployment process.

NOTE: As these changes propagate through the pipeline (e.g. we merge `develop` into `staging` with these changes) the ansible playbooks defined in the [CantusDB ansible repo](https://github.com/dact-chant/ansible.cantus-db) should be used for deployment.

What this means:

- cron jobs and nginx configurations will be managed by the playbook, so these can be removed. `cantusdb.conf.development` is retained for use in local development
- shell scripts used in cron jobs have been modified so that parameters are defined by command-line arguments. This means they can be modified in the playbook (ie. as the arguments passed in) rather than in the script itself.
- A single docker-compose.yml is necessary for all remote deployments. If port mapping on the `django` container is desired for local development, I've kept the `docker-compose.yml.development` file that can be used. 
- The nginx configuration defined in the ansible playbook redirects all requests to any host alias (e.g. `mass.cantusdatabase.org`) to the canonical host (e.g. `cantusdatabase.org`). Therefore, only a single `ALLOWED_HOSTS`, etc. is needed in django's `settings.py`. Note: we'll need to work in the checks introduced in #1384.

Significant changes to the wiki (both the one on GitHub and the DDMAL one) will be required with this PR. I can edit those now so they can be reviews along with this PR? Or wait until the PR is merged and then do them? Thoughts? 

In preparing this PR, git discovered that on the staging branch we have a `contact_form.html` template that we don't have on the develop branch (see [05d2f7f](https://github.com/DDMAL/CantusDB/pull/1386/commits/05d2f7ffd5553d0824cba416d395a0588e7fe674)). This template seems to be duplicated by the `contact.html` template that we have on both the `develop` and `staging` branches. Any thoughts about that?

### CODE REVIEW

**Comment by ahankinson** [comment]
Looks ok to me!

**Comment by jacobdgm** [comment]
> Significant changes to the wiki (both the one on GitHub and the DDMAL one) will be required with this PR. I can edit those now so they can be reviews along with this PR? Or wait until the PR is merged and then do them? Thoughts?

I think you can fork the wiki and make a PR with updated documentation that can be merged upon the merging of this PR - does this sound like the right approach?

> In preparing this PR, git discovered that on the staging branch we have a `contact_form.html` template that we don't have on the develop branch (see [05d2f7f](https://github.com/DDMAL/CantusDB/pull/1386/commits/05d2f7ffd5553d0824cba416d395a0588e7fe674)). This template seems to be duplicated by the `contact.html` template that we have on both the develop and staging branches. Any thoughts about that?

Relevant: https://github.com/DDMAL/CantusDB/pull/477#issuecomment-1354799601 - a couple of years ago, something went amiss with merges related to a hotfix. `contact_form.html` should be removed.

(As an aside, contact.html is so simple that we should probably just get rid of the view and make it a flatpage. Let me open an issue about this)

**Comment by dchiller** [comment]
> I think you can fork the wiki and make a PR with updated documentation that can be merged upon the merging of this PR - does this sound like the right approach?

Do you know how to do this? Pointers would be helpful because I have thus far failed! My fork, for example, has no wiki...

**Comment by jacobdgm** [comment]
https://stackoverflow.com/questions/7197937/on-github-can-i-fork-just-a-wiki

Maybe you don't need a full fork, but you could try something along the lines of `git clone https://github.com/ddmal/cantusdb.wiki.git`?

Interestingly, looking at the comments in the SO discussion, it seems that if you make a proper fork, you can't open a PR to contribute back to the initial wiki. So maybe the approach here is just to clone, make changes locally, and then push directly to DDMAL/CantusDB? I guess this is a tiny bit more work than simply merging this PR and then writing the documentation afterwards, but this at least would allow the updated documentation to be displayed right away.

**Comment by dchiller** [comment]
Ok, I have now made changes to the wiki(s):

- On the DDMAL internal wiki, I have edited the `dev_env` file that will be needed once this PR is merged. 
- On the CantusDB wiki (here on GitHub), I have:
  - edited instructions for local deployment and placed this on a renamed page [Deploying CantusDB locally for development](https://github.com/DDMAL/CantusDB/wiki/Deploying-CantusDB-locally-for-development). Updated link to this page on wiki home page.
  - edited [instructions for how to update the servers](https://github.com/DDMAL/CantusDB/wiki/Updating-the-Staging-and-Production-Servers)
  - combined instructions for how to manage SSL certificates on a [single page](https://github.com/DDMAL/CantusDB/wiki/Managing-SSL-certificates)
  - created a [new page](https://github.com/DDMAL/CantusDB/wiki/Populating-the-database) that includes information on populating a new database (this mainly copied existing information, but puts it on its own page) 
  - Added instructions for manual backups and changed cron-related instructions to the [Backups page](https://github.com/DDMAL/CantusDB/wiki/Backups)

I wasn't able to push my changes directly to the wiki (it looks like wiki repositories may only support https access?), so I just copied my changes in manually.

**Comment by dchiller** [comment]
> `contact_form.html` should be removed.

Just did this :)

**Comment by jacobdgm** [comment]
I've been thinking of putting some updated code on the Staging server today for testing - guessing that now would be a good time to merge this and test it out? We're not waiting on anything else, are we?

I'll take another look through the code for this PR so I can give a proper approval.

**Review by jacobdgm — APPROVED** [review]

**Comment by dchiller** [comment]
> I've been thinking of putting some updated code on the Staging server today for testing - guessing that now would be a good time to merge this and test it out? We're not waiting on anything else, are we?

I think the only thing to consider here is that the current staging and production servers are not set up for ansible. The new staging server is the only one set up for ansible at the moment. So, once this PR propagates to `staging` we don't want to use the old staging server anymore, and then once it propagates to `production` we will want to be ready with the new production server (or in the interim we can set up the old production server to use ansible).

I think my suggested sequence would be as follows:
1. Merge `develop` to `staging` and deploy to the old staging server as you have usually done. This will be the last update to the old staging server.
2. Merge this PR to `develop`.
3. @jacobdgm and @lucasmarchd01 test that they can deploy `develop` branch locally without issue.
4. Merge `develop` to `staging` and deploy to the new staging server using ansible. At this point, the code bases on old staging and new staging will be the same except for the changes included in this PR. 

This way we'll have tested that people besides me can get this running locally for development and can use ansible to deploy to a remote server. 

Once we're satisfied with this, we can:
5. Remove old staging server.
6. Create new production server. 
7. Deploy to production. 

I don't think we should not plan to tackle these last three steps before the weekend. But maybe we can plan to do the production switchover sometime next week? We'll want to alert Debra and Jennifer and "close down" production for editing for some period of time while that's happening.

It hopefully goes without saying but please ask questions and push back with alternatives, especially here! I wanna make sure we do this transition without breaking anything!

**Comment by jacobdgm** [comment]
> I think the only thing to consider here is that the current staging and production servers are not set up for ansible. The new staging server is the only one set up for ansible at the moment. So, once this PR propagates to `staging` we don't want to use the old staging server anymore, and then once it propagates to `production` we will want to be ready with the new production server (or in the interim we can set up the old production server to use ansible).
> 
> I think my suggested sequence would be as follows:
> 
> 1. Merge `develop` to `staging` and deploy to the old staging server as you have usually done. This will be the last update to the old staging server.
> 2. Merge this PR to `develop`.
> 3. @jacobdgm and @lucasmarchd01 test that they can deploy `develop` branch locally without issue.
> 4. Merge `develop` to `staging` and deploy to the new staging server using ansible. At this point, the code bases on old staging and new staging will be the same except for the changes included in this PR.
> 
> This way we'll have tested that people besides me can get this running locally for development and can use ansible to deploy to a remote server.
> 
> Once we're satisfied with this, we can: 5. Remove old staging server. 6. Create new production server. 7. Deploy to production.

This all makes sense, and your suggested plan sounds good.

> I don't think we should not plan to tackle these last three steps before the weekend. But maybe we can plan to do the production switchover sometime next week? We'll want to alert Debra and Jennifer and "close down" production for editing for some period of time while that's happening.

If I recall, it's not urgent that we set up the new production server immediately-ish, correct? We could create the new staging server next week (Apr 11 or 12, say), and once that has gone well, we can let Debra and Jennifer know that we'll be proceeding with the Production switchover the following week (April 18 or 19, say)?

**Comment by dchiller** [comment]
> We could create the new staging server next week (Apr 11 or 12, say)

This is already done. See staging.new.cantusdatabase.org. 

> it's not urgent that we set up the new production server immediately-ish, correct?

One week is not going to make a difference. I think the main thing is that if we want to keep our pipeline intact (in other words, only merge to `production` from `staging` from `development` then we need to be ok with holding off on other changes to production until we have transitioned to the new server)

**Comment by ahankinson** [comment]
I'm around in Halifax this weekend, and can assist on Monday with any transitions. I can set up a new production server pretty quickly on Arbutus, and have some testing methods (do you guys know about the `hosts` file trick?) that can help with the switch.

**Comment by jacobdgm** [comment]
> I'm around in Halifax this weekend, and can assist on Monday with any transitions. I can set up a new production server pretty quickly on Arbutus, and have some testing methods (do you guys know about the `hosts` file trick?) that can help with the switch.

@dchiller, do we think it makes sense to try to do the switchover for the Production machine this coming Monday?

Moving pieces should consider:
- We need Debra to help us log into Hover to make the necessary DNS changes
- We might consider contacting Debra and/or Jennifer to communicate to contributors that CantusDB will be unavailable for a little while (I'm imagining we set up the new Production VM, turn off people's login access on the old Prod VM, export a database dump, load the dump into the new Prod VM, and change the DNS settings - I'm imagining this will take <30 minutes, so maybe we ask for one hour to do it all: 15h-16hET? - does this sound like a reasonable set of steps and precautions?)

@ahankinson, nope, I don't know to which "hosts file trick" you're referring. But I'd appreciate your being on standby to help with anything that arises - this, in my mind, is a compelling reason to do the switchover as early as this coming Monday.

**Comment by jacobdgm** [comment]
actually, back up. Normally, I do work for the lab on Tuesdays and not Mondays. I was considering making an exception for this Monday.

But there's an eclipse on Monday, so I am definitely going to be taking this day off.

**Comment by ahankinson** [comment]
https://docs.hypernode.com/best-practices/testing/how-to-test-your-website-by-changing-your-hosts-file.html

**Comment by dchiller** [comment]
> do we think it makes sense to try to do the switchover for the Production machine this coming Monday?

I think it would make sense for you or @lucasmarchd01 to update the new staging server early next week post-eclipse (say, Tuesday; this will be a good check on my work) and then later in the week we can do production. 

Andrew's trick sounds good, but we'll need to make a few changes so that not being able to get a certificate doesn't stop the process.

**Pull request merged**
