### PR TITLE
Update configurations for development processes

### PR DESCRIPTION
**Pull request by dchiller**
This PR updates some docker configurations for the development process, specifically for use with DevContainers. 

- The repo has two versions of a docker compose file. One, `docker-compose-development.yml` can be used for development without DevContainers. The other, `docker-compose-dev-containers.yml` can be used for development with DevContainers.
- A deployment version of `docker-compose.yml` is no longer included in this repo. It will be templated in the ansible repo (see https://github.com/dact-chant/ansible.cantus-db/issues/33).
- The `debug` dependency group is removed. Its contents are included in the `dev` dependency group.
- Django's `runserver`, rather than `gunicorn`, is used in development.
- Some additional `dev` dependencies are added for linting and typing Django.

### CODE REVIEW

**Comment by lucasmarchd01** [comment]
Nice! The devcontainer is working for me now. There's one thing still that I wonder if we can change.

When I open a new terminal inside the container, it opens to `root@06fc3800d28a:/code/cantusdb_project#`. I'm not sure if it's better to have it this way but when I want to run any django management commands like runserver for example I have to `cd` into `/code/cantusdb_project/django/cantusdb_project` each time.

Also I tested making a commit to the branch and runinto an error that says ".git/hooks/pre-commit: 1: black: not found" even though I have black installed as both an extension in the devcontainer.json file and as an extension in VS code. I'll keep playing around with it in case it is something silly on my end. Dylan are you running into any issues like this as well?

**Comment by lucasmarchd01** [comment]
Hmm.. And then when I try and make a commit outside of the dev container I get:
```
2024-05-08 10:01:02.520 [info] would reformat /Users/lucasmarch/Projects/CantusDB/django/cantusdb_project/articles/migrations/0001_initial.py
would reformat /Users/lucasmarch/Projects/CantusDB/django/cantusdb_project/main_app/migrations/0003_alter_chant_source_alter_sequence_source.py
would reformat /Users/lucasmarch/Projects/CantusDB/django/cantusdb_project/main_app/migrations/0007_rename_differentia_new_chant_differentiae_database_and_more.py
would reformat /Users/lucasmarch/Projects/CantusDB/django/cantusdb_project/main_app/migrations/0004_alter_chant_source_alter_sequence_source.py
would reformat /Users/lucasmarch/Projects/CantusDB/django/cantusdb_project/main_app/migrations/0006_alter_chant_melody_id_alter_sequence_melody_id_and_more.py
would reformat /Users/lucasmarch/Projects/CantusDB/django/cantusdb_project/main_app/migrations/0005_alter_chant_ah_volume_alter_chant_cantus_id_and_more.py
would reformat /Users/lucasmarch/Projects/CantusDB/django/cantusdb_project/main_app/migrations/0008_differentia_chant_diff_db_sequence_diff_db.py
would reformat /Users/lucasmarch/Projects/CantusDB/django/cantusdb_project/users/migrations/0001_initial.py
would reformat /Users/lucasmarch/Projects/CantusDB/django/cantusdb_project/main_app/migrations/0001_initial.py
would reformat /Users/lucasmarch/Projects/CantusDB/django/cantusdb_project/main_app/tests/test_views.py

Oh no! 💥 💔 💥
10 files would be reformatted, 75 files would be left unchanged.
```
but running `black .` leaves all files unchanged.

**Comment by dchiller** [comment]
> Hmm.. And then when I try and make a commit outside of the dev container I get:
> 
> ```
> 2024-05-08 10:01:02.520 [info] would reformat /Users/lucasmarch/Projects/CantusDB/django/cantusdb_project/articles/migrations/0001_initial.py
> would reformat /Users/lucasmarch/Projects/CantusDB/django/cantusdb_project/main_app/migrations/0003_alter_chant_source_alter_sequence_source.py
> would reformat /Users/lucasmarch/Projects/CantusDB/django/cantusdb_project/main_app/migrations/0007_rename_differentia_new_chant_differentiae_database_and_more.py
> would reformat /Users/lucasmarch/Projects/CantusDB/django/cantusdb_project/main_app/migrations/0004_alter_chant_source_alter_sequence_source.py
> would reformat /Users/lucasmarch/Projects/CantusDB/django/cantusdb_project/main_app/migrations/0006_alter_chant_melody_id_alter_sequence_melody_id_and_more.py
> would reformat /Users/lucasmarch/Projects/CantusDB/django/cantusdb_project/main_app/migrations/0005_alter_chant_ah_volume_alter_chant_cantus_id_and_more.py
> would reformat /Users/lucasmarch/Projects/CantusDB/django/cantusdb_project/main_app/migrations/0008_differentia_chant_diff_db_sequence_diff_db.py
> would reformat /Users/lucasmarch/Projects/CantusDB/django/cantusdb_project/users/migrations/0001_initial.py
> would reformat /Users/lucasmarch/Projects/CantusDB/django/cantusdb_project/main_app/migrations/0001_initial.py
> would reformat /Users/lucasmarch/Projects/CantusDB/django/cantusdb_project/main_app/tests/test_views.py
> 
> Oh no! 💥 💔 💥
> 10 files would be reformatted, 75 files would be left unchanged.
> ```
> 
> but running `black .` leaves all files unchanged.

So you are running `black .` outside the dev container and the commit outside the container in this case? What version of black is running from the command line? What version in the git hook? I wonder if there are two different versions running?

**Comment by lucasmarchd01** [comment]
Yes, running `black .` outside of the container through terminal in the venv works fine. Using source control in VS code (still outside the devcontainer) runs into this issue. I have the poetry venv selected as the interpreter.

I see that the git hook is running on black version 23.3.0 but our poetry venv uses black version 24.4.2. Should we be using poetry's pre-commit hooks?
https://python-poetry.org/docs/pre-commit-hooks/

**Comment by dchiller** [comment]
> When I open a new terminal inside the container, it opens to `root@06fc3800d28a:/code/cantusdb_project#`. I'm not sure if it's better to have it this way but when I want to run any django management commands like runserver for example I have to `cd` into `/code/cantusdb_project/django/cantusdb_project` each time.

Ok, it looks like we can solve this by changing `workspaceFolder` in `devcontainer.json` to "/code/cantusdb_project/django/cantusdb_project".

Side note: are you running `runserver`? Do you stop the `gunicorn` process? What happens? I think we should use `runserver` in development but just saw that the container command used `gunicorn` so left it for now.

**Comment by dchiller** [comment]
> I see that the git hook is running on black version 23.3.0 but our poetry venv uses black version 24.4.2.

I would run the git hook in the poetry environment if you are going to use poetry. So prepend `poetry run` to the `black` command in the git hook.

(I would also update black in whatever environment the git hook was previously using to be in the 2024 style)

**Comment by dchiller** [comment]
> Also I tested making a commit to the branch and runinto an error that says ".git/hooks/pre-commit: 1: black: not found" even though I have black installed as both an extension in the devcontainer.json file and as an extension in VS code. I'll keep playing around with it in case it is something silly on my end. Dylan are you running into any issues like this as well?

Does the black extension work **not** in the git hook? Like when you save a file?

Regardless, I think the way to solve this would be to add black to the inside-the-container environment for development. So, get rid of the distinction between `debug` and `dev` dependecy groups, and install all of them *inside* the container for development. Because I wasn't thinking about dev containers when making the switch to poetry, I had them separated.

For now, why don't you move `black` from the `dev` to the `debug` group in `pyproject.toml` and see if that works.

**Comment by lucasmarchd01** [comment]
> Does the black extension work not in the git hook? Like when you save a file?

Yes

> For now, why don't you move black from the dev to the debug group in pyproject.toml and see if that works.

This did the trick for me, thanks! So are we getting rid of the `dev` group entirely in `pyproject.toml`? Does that interfere with anything else in the workflow?

**Comment by lucasmarchd01** [comment]
> Side note: are you running runserver? Do you stop the gunicorn process? What happens? I think we should use runserver in development but just saw that the container command used gunicorn so left it for now.

I don't have to stop anything with the gunicorn process. I forward the port to 8888 and everything seems to work fine.

**Comment by dchiller** [comment]
> I don't have to stop anything with the gunicorn process. I forward the port to 8888 and everything seems to work fine.

Ok, interesting...well, if the new devcontainer.json works for you, let's keep it.



> This did the trick for me, thanks! So are we getting rid of the `dev` group entirely in `pyproject.toml`? Does that interfere with anything else in the workflow?

I think let's just move everything from debug to dev and install it all in the devcontainer. Doesn't interfere with other things...I'll commit that change here.

**Review by lucasmarchd01 — APPROVED** [review]
Tested both configurations and everything works for me! Thanks for setting this up.

**Pull request merged**
