### PR TITLE
 Set up redirects for /indexer/ urls

### LINKED ISSUE #715: we should set up redirects from /indexer/<id> urls to corresponding user detail page
Now that all indexers in NewCantus are represented as users rather than as Indexer objects, we need to set up redirects from old `/indexer/<indexer id>` paths, which no longer work, to the corresponding/proper `/user/<user id>` page.

### PR DESCRIPTION
**Pull request by PythonSemicolon**
OldCantus /indexer/ urls now redirect to their corresponding /user/ page in NewCantus, if found; otherwise, a 404 is returned. Included test cases and docstring for new view method.

### CODE REVIEW

**Comment by jacobdgm** [comment]
This looks good, and is basically ready to approve - just waiting on a couple of tweaks to #716...

**Comment by PythonSemicolon** [comment]
Manually rebased and updated test style & method calls to match those from latest develop merge. Ready for re-review @jacobdgm

**Comment by PythonSemicolon** [comment]
Refactored, fixed typos @jacobdgm

**Review by jacobdgm — APPROVED** [review]
Great - thanks!

**Pull request merged**
