### PR TITLE
Merge staging into production, 2023 Nov 10 edition

### PR DESCRIPTION
**Pull request by jacobdgm**
When updating production, we need to remember to run `python manage.py add_differentiae`.

Nov 15 update: new code is running on staging, and all tests are passing.

Nov 21 update: the changelog is complete! let testing commence!

Changes:
- [x] general:
  - [x] There is now a script to remap user contributions (e.g. who created which source, etc.). This needs to be tested on staging, and @annamorphism needs to verify that it worked properly before we run it on production.
    - [x] this script appears to have bugs, so we've disabled it for now
- [x] all pages
  - [x] footer:
    - [x] the email icon in the footer now sends an email to Debra's email address rather than cantus@cantusindex.org
    - [x] the copyright year has been updated from 2022 to 2023
- [x] Admin Area
  - [x] Change Chant
    - [x] old differentiae_database field has been hidden (this field has been replaced by the diff_db field (labelled "differentiae database"). the differentiae_database field will eventually be removed entirely)
  - [x] Source Change
    - [x] "source status" field is now hidden
- [x] Chant Create
  - [x] there now exists a Differentiae Database autofill field
  - [x] Office and Genre fields are now autocomplete fields
  - [x] Office, Genre, Feast autocomplete fields search for `contains` matches instead of just `startswith`
  - [x] Feast autocomplete no longer searches by feast code
  - [x] we no longer send requests to CI when loading this view, and we no longer suggest fulltexts for new chants (we plan to reintroduce this feature in the near future)
- [x] Chant Detail
  - [x] Differentiae Database snippets are now displayed
  - [x] we no longer send requests to CI when loading this view, and the concordances tables have been replaced with a message directing people to CI
- [x] Chant Edit
  - [x] there now exists a Differentiae Database autofill field
  - [x] we no longer send requests to CI when loading this view, and we no longer suggest fulltexts for chants without fulltexts (we plan to reintroduce this feature in the near future)
  - [x] Office, Genre, Feast autocomplete fields search for `contains` matches instead of just `startswith`
  - [x] Feast autocomplete no longer searches by feast code
- [x] Chant Search
  - [x] users can no longer search for chants without melodies
- [x] CI Search
  - [x] this view has been temporarily removed (we plan to reimplement this view in the near future)
- [x] Full Index
  - [x] we've added a "DD" (i.e., Differentiae Database) column
- [x] Melody Search page
  - [x] fixed bug with melody search interface where it would break when window was resized
  - [x] fixed bug with interface where staff would spill onto a second line when the window was narrow
- [x] Source Create
  - [x] Provenance is now an Autocomplete field
- [x] Source Detail
  - [x] previously, source _descriptions_, _liturgical occasions_ and _selected bibliographies_ would all run together onto single lines. Line breaks are now preserved.
- [x] Source Edit
  - [x] Provenance is now an Autocomplete field
- [x] under the hood:
  - [x] the urllib3 version was bumped from 1.26.5 to 1.26.17
  - [x] `Chant.differentiae_new` was renamed to `.differentiae_database`
  - [x] all pages now send traffic reports to Google Analytics (this will only be present on production)
  - [x] A new DifferentiaeDatabase model has been added - see Chant Create/Detail/Edit. As of the evening of Wed Nov 15, I'm running `python manage.py add_differentiae` on staging, and this will also need to be run on Production

### CODE REVIEW

**Comment by jacobdgm** [comment]
nota bene! As I was putting together an email to Debra telling her about the changes relating to #1100, I noticed some inconsistencies that we should address address before putting this up on production (see #1147, #1148, #1149). Then, after some investigation/deliberation/contemplation, it was decided that it made most sense to roll back #1100 to allow testing to proceed.

In order to proceed, we need to:
- [x] approve #1151 
- [x] merge develop into staging again, and update the staging server
- [x] compile changelog and begin testing

**Comment by jacobdgm** [comment]
sigh... I just found #1161. Going to have to fix that first before we continue testing...

update: I just opened #1162. Waiting for approval before merging into the staging branch and updating the staging server.

update: #1162 is merged, and the changes are running on the staging server!

**Comment by jacobdgm** [comment]
update: #1165 has been discovered, so we did #1167. This change still needs to make its way to the Staging machine.

The internet at McGill isn't working today, so I've gone to a library to attempt to get _something_ done. I had hoped to update staging from here, but naturally, I can't ssh into staging because I can't ssh into the jumpbox. Updating staging will have to wait for another day - hopefully McGill's internet will be doing better tomorrow.

**Comment by jacobdgm** [comment]
#1167 has been implemented, the new code is running on Staging, and all tests are passing!

**Comment by jacobdgm** [comment]
@lucasmarchd01 @dchiller @annamorphism can one of you approve this before I merge it?

**Review by lucasmarchd01 — APPROVED** [review]

**Pull request merged**
