### PR TITLE
Footer: Remove links to databases other than Cantus Index

### LINKED ISSUE #1103: We should clean up links in the footer
From debra:

> At the bottom of NewCantus we have a list of links to some of the Cantus Index networked databases. This appears to be historic in having just a few of them, and I'm sure it's what was on OldCantus for many years, esp at the time when OldCantus was young.
> 
> Can we have just "Cantus Index" there? Or, since Cantus Index is in one of the texts above, what if I were to rewrite that text and make the link to Cantus Index a bit nicer looking? Then, we would remove the links to databases section at the bottom.
> 
> https://cantusdatabase.org/
> This is the page, for quick reference. I think it's time to update the look of the page. I like the top two sections (up to the Cantus Index link), and then I think we could jump right to the EDI statement.
> 
> There might still be a use for the "Use Cantus Database if ..." and "Use Cantus Index if ...." sections but maybe they can be elsewhere or folded away on this page so it doesn't look so cluttered.

### PR DESCRIPTION
**Pull request by jacobdgm**
fixes #1103

How it looks now:

Logged out:
Screenshot 2023-12-07 at 1 25 27 PM
[Previous version](https://github.com/DDMAL/CantusDB/assets/58090591/60613512-7c69-4cc5-930b-8cbf7124426b)

Logged in:
Screenshot 2023-12-07 at 1 25 42 PM
[Previous version](https://github.com/DDMAL/CantusDB/assets/58090591/08423240-e039-4b4f-bec4-28824a9d8f39)

Logged in, narrow window:
Screenshot 2023-12-07 at 1 26 03 PM
[Previous version](https://github.com/DDMAL/CantusDB/assets/58090591/33481530-c752-47dc-8e50-97e240d13ad0)

### CODE REVIEW

**Comment by jacobdgm** [comment]
Without a bunch of links to other databases, the link to CI looks a bit lonely. Open to suggestions as to how to improve this.

**Comment by dchiller** [comment]
> Without a bunch of links to other databases, the link to CI looks a bit lonely. Open to suggestions as to how to improve this.

Hmmm... it does indeed, and also the "Database Links" header (in plural) is lying. Maybe there could be a sentence describing what Cantus Index is; in other words, why you would click on such a link?

**Comment by annamorphism** [comment]
I had the same thoughts and see they've already been mentioned! Maybe this would be better replaced altogether with some sort of "Part of the _Cantus Index_ Network link/logo. I would show this screenshot to Debra and ask. (I think she proposed getting rid of it, since there is text about Cantus Index on the Home page, but the footer shows up more places than the explainer text does.)

**Comment by jacobdgm** [comment]
We just got an email from Debra about this:

> Jennifer and I looked at the screenshots of having just Cantus Index under the list of links, and we think we should just take it out altogether.
> 
> The link to Cantus Index is in the text in the main part of the page (at the top), so it's unnecessary. And, we don't want to duplicate the complete list of links here since they're already on the Cantus Index site (too much to edit and keep track of).
> 
> So, please remove the heading and content under "Database Links".  Thank you!

I'll implement this and request people's reviews again.

**Comment by jacobdgm** [comment]
I've entirely removed the "Database Links" section as requested. Screenshots have been updated - this PR is ready again for review!

**Review by dchiller — APPROVED** [review]

**Pull request merged**
