### PR TITLE
Merge staging into production - 2023-02-10 edition

### PR DESCRIPTION
**Pull request by jacobdgm**
Hoping that by starting testing now we can move the changes to production faster than last time ^^

Pages affected by these changes:
- Article Detail page
  - in template, change how URLs are fetched/generated ([commit](https://github.com/DDMAL/CantusDB/pull/549/commits/29d7cd304667fdc6773720cff91a7692bb09dc73))
  - add missing `<title>` tags ([commit](https://github.com/DDMAL/CantusDB/pull/549/commits/4cf3c7b428f3c3ce4b8d93f9f3a6680e11d0cab8))
- Article List page
  - in template, change how URLs are fetched/generated ([commit](https://github.com/DDMAL/CantusDB/pull/549/commits/0cadac71132697ec2a74382cebf96276f930be18))
  - add missing `<title>` tags ([commit](https://github.com/DDMAL/CantusDB/pull/549/commits/84b7e9f4bbfe0146e19489fd4c0f1a26ab5c83e9))
- Cantus Index Input Tool page
  - fix bug where table would be very narrow when viewed in Firefox
  - fix bug where pressing the "OK" button would not update the Genre field on the main Create Chant page.
  - when you press "OK", the CI Input Tool window now closes itself.
- Century Detail page
  - change how URLs are fetched/generated
  - ensure that only links to sources that user can view are displayed in the list of sources (i.e. hide unpublished sources for anonymous users)
- Chant Create page
  - change how URLs are fetched/generated
  - move addendum field away from bottom of page
- Chant Detail page
  - in the sidebar and a couple of other places, links beginning with "»" each occupy their own line, and the template has been tidied up. Other than the links each beginning on their own line, the guillemet should appear the same as before. ([commit](https://github.com/DDMAL/CantusDB/pull/549/commits/03e4bd8e26c0e952c6bf23c7ecea850e26e92c02))
  - change how URLs are fetched/generated
  - add title attributes in several places
  - add bold formatting to current chant in sidebar
  - some refactoring of logic
  - fix bug occurring when chant has volpiano but no fulltext/incipit
  - if you edit a chant from the Chant Detail page, you're now directed back to the Chant Detail page upon saving the chant.
  - refactor how the concordances summary is generated
- Chant Edit page
  - text-and-melody preview is now directly below the Volpiano field. ([commit](https://github.com/DDMAL/CantusDB/pull/549/commits/be06459e96a9b1e07c4abc41b74bf3a8c4acc120), [commit](https://github.com/DDMAL/CantusDB/pull/549/commits/f6a7b57efaeda979174bb576f69e62ba70f34e6d))
  - "Edit syllabification" link no longer has an unnecessary colon, and is now below the text-and-melody preview ([commit](https://github.com/DDMAL/CantusDB/pull/549/commits/72b2a8c6042bc78e6c7b9a35c6c67fb3de94ca3c), [commit](https://github.com/DDMAL/CantusDB/pull/549/commits/f6a7b57efaeda979174bb576f69e62ba70f34e6d))
  - change how URLs are fetched/generated
  - add title attributes in several places
  - fix bug occurring when chant has volpiano but no fulltext/incipit
  - add addendum field
  - Folio, Sequence, etc. fields are now above manuscript text fields
- Chant List page
  - in the sidebar, links beginning with "»" each occupy their own line, and the template has been tidied up. Other than the links each beginning on their own line, the guillemet should appear the same as before. ([commit](https://github.com/DDMAL/CantusDB/pull/549/commits/03e4bd8e26c0e952c6bf23c7ecea850e26e92c02))
  - change how URLs are fetched/generated
  - fix bug occurring when we try to display a chant that is missing one or more related object (feast, office, genre)
  - add a title attribute
  - if you edit a chant from the Chant List page, you're now directed back to the Chant List page upon saving the chant.
  - reorder chants by folio and c_sequence
- Chant Proofread page
  - text-and-melody preview is now directly below the Volpiano field ([commit](https://github.com/DDMAL/CantusDB/pull/549/commits/0ea3214bc69c17504013e08ae6f6f50cbd18f5b3)).
  - change how URLs are fetched/generated
  - add title attributes in several places
  - fix bug occurring when chant has volpiano but no fulltext/incipit
  - add link pointing to the Edit Syllabification page
  - remove siglum and syllabification fields
- Chant Search page
  - change how URLs are fetched/generated
  - fix bug occurring when we try to display a chant that is missing one or more related object (feast, office, genre)
  - add title attributes to feasts
  - Chant Search page now uses django query built-ins instead of `keyword_search()`
  - change how querysets are unioned
  - tweak logic so that if an operation is not specified in the URL query parameters, we default to a fast `startswith` search
  - some other refactoring
- Chant Search MS page
  - update view to match Chant Search template, which this page uses
- Chants and Sequences by Cantus ID page
  - change how URLs are fetched/generated
  - add links to office and genre detail pages
  - fix bug occurring when we try to display a chant that is missing one or more related object (feast, office, genre, source)
  - tidy up template
  - add title attribute
- Feast Detail page
  - change how URLs are fetched/generated
  - fix bug that occurs when the representative chant has no Genre ([commit](https://github.com/DDMAL/CantusDB/pull/549/commits/5453652cb532fa369240cd10b58ecdb2a36570ce))
- Feast List page
  - change how URLs are fetched/generated
  - add title attribute to feast.name ([commit](https://github.com/DDMAL/CantusDB/pull/549/commits/e6ab643182cf25d07875918e04f3ab472af50cbc))
  - tidy up template
- Full inventory page
  - Where the page said "index", it now says "inventory" ([commit](https://github.com/DDMAL/CantusDB/pull/549/commits/e401658a0150bd08d690fd7e2e25b282eaa6c371))
  - change how URLs are fetched/generated
  - add title attribute where siglum is displayed ([commit](https://github.com/DDMAL/CantusDB/pull/549/commits/4632e9ae9bcd8b7e3a1cfa636e64ecb49c543ba0)), and other place(s)
  - fix error where invalid links would be generated for sequences listed in the index
  - ordering of inventory has been improved for sources in the Bower segment (i.e. we now sort by `s_sequence` and ignore `folio`)
- Genre Detail page
  - remove list of chants associated with the genre ([commit](https://github.com/DDMAL/CantusDB/pull/549/commits/133cb8f34ef9456779fe67f3c43aed4299afa21f))
  - change how URLs are fetched/generated
- Genre List page
  - change how URLs are fetched/generated
- Indexer List page
  - change how URLs are fetched/generated
- Melody Search page
  - change how URLs are fetched/generated
- Notation Detail page
  - change how URLs are fetched/generated
- Office List page
  - change how URLs are fetched/generated
- Provenance Detail page
  - change how URLs are fetched/generated
- Sequence Detail page
  - change how URLs are fetched/generated
  - fix bug occurring when sequence has no source
- Sequence List page
  - change how URLs are fetched/generated
  - fix bug occurring when we try to display a sequence with no source
  - add title attribute where we display a source's siglum
- Source Detail page
  - "View full index" now reads "view full inventory" ([commit](https://github.com/DDMAL/CantusDB/pull/549/commits/24427179af4f9f6d7ad1f002ac3abaae0fccad37))
  - in the sidebar, links beginning with "»" each occupy their own line, and the template has been tidied up. Other than the links each beginning on their own line, the guillemet should appear the same as before. ([commit](https://github.com/DDMAL/CantusDB/pull/549/commits/03e4bd8e26c0e952c6bf23c7ecea850e26e92c02))
  - change how URLs are fetched/generated
  - add title attribute to displayed siglum
- Source List page
  - In the "Chants/Melodies" column, if a source has 0 chants, "0" is now displayed instead of "None" ([commit](https://github.com/DDMAL/CantusDB/pull/549/commits/0eece02dcfbd626fdf1ad744feaaa8569238eb7a)).
  - change how URLs are fetched/generated
- User Detail page
  - change how URLs are fetched/generated
  - add title attribute where source siglum is displayed
- User List page
  - change how URLs are fetched/generated
- User Source List page
  - instead of displaying sources' titles, we now display their sigla
- general:
  - base.html (i.e. all pages)
    - add logo/link to MARGOT in footer
    - change UW logo to link to UW, not MARGOT
    - subsequently, crop negative space around logo text
  - requirements.txt
    - bump django to 4.1.7 ([commit](https://github.com/DDMAL/CantusDB/pull/549/commits/ea1fe590c0ec51139da866d6ebbb12885d7016c3))
    - bump asgiref ([commit](https://github.com/DDMAL/CantusDB/pull/549/commits/887452205bca5604e81faaa9af58fa77bfeac23f))
    - add django_debug_toolbar ([commit](https://github.com/DDMAL/CantusDB/pull/549/commits/887452205bca5604e81faaa9af58fa77bfeac23f))
  - update ChantSearchViewTest
  - update ChantSearchMSViewTest
  - update ChantEditViewTest
  - update ChantProofreadViewTest
  - fix bug in make_fake_source, and tweak function to add `century` parameter
  - remove `keyword_search()` function

The browsers I have available to me - if anyone else would like to participate, feel free to check these off or add additional ones.
- [x]  Safari (Jacob is working through the list on Safari - has gotten as far as Feast Detail page)
- [ ]  Firefox (Lucas is working in Firefox)
- [ ]  Chrome (dchiller is starting from the top on Chrome)

### CODE REVIEW

**Comment by jacobdgm** [comment]
before we begin testing, let's include PR #551 as part of this update.

**Comment by dchiller** [comment]
> before we begin testing, let's include PR #551 as part of this update.

Now approved!

**Comment by jacobdgm** [comment]
> Now approved!

And now merged! The staging branch has been updated, and the staging server is now running the updated code!

**Comment by dchiller** [comment]
@jacobdgm Happy to do some poking around on the staging site on my devices....but realizing I don't actually know where it is!

**Comment by jacobdgm** [comment]
staging: http://206.12.88.113
production: http://206.12.93.196

**Comment by jacobdgm** [comment]
I was trying to get this fully tested and merged so we could upload the changes to the Chant Search page to `staging` and see how it performs on the DRA server. But having discovered #574, which feels important enough that it should be fixed right away, I'm setting testing aside for the time being. I'll fix #574, merge develop into staging, and start testing again, including all the recent changes.

**Comment by jacobdgm** [comment]
with #580, we have a fix for #574, as well as improvements to the Chant Search page and a few other small tweaks. I've edited the list of changes above; staging is now running the updated code, and all tests are passing. Let testing resume!

**Comment by jacobdgm** [comment]
Just found #581 - I don't think it's big enough to prevent us from taking these changes to production, but it should be fixed sometime soon.

This bug is also present on production, so it hasn't been introduced by a recent change.

**Comment by jacobdgm** [comment]
#581 has been fixed, as well as #584 and #583! Let testing resume! Hopefully no more bugs that will cause things to grind to a halt again.

**Comment by jacobdgm** [comment]
So the app running on staging is currently down. It appears that the staging branch was updated, but I forgot to `git pull` on the staging server to run the changed code. A change to a type annotation (which is supported in python>=3.9 but not 3.8) is preventing the app from running. #589 should solve this into the future I think. Currently working to make the necessary change directly on the server to fix things for the time being - updates to follow!

Update 2023 Mar 16 15h40EDT: On the staging server, I tried taking the docker container down, deleting images, updating the python version listed in the Dockerfile, running `docker-compose build`, and running `docker-compose up -d`. It seems to have solved the `TypeError` (or similar) that was occurring previously, but now the django app can't find postgres:

```bash
jacob@cantus-db-stag:/home/cantusdb/CantusDB$ docker-compose exec django bash
root@8d0fa925e23a:/code/django/cantusdb_project# python manage.py makemigrations
/usr/local/lib/python3.9/site-packages/django/core/management/commands/makemigrations.py:143: RuntimeWarning: Got an error checking a consistent migration history performed for database connection 'default': could not translate host name "postgres" to address: Temporary failure in name resolution

  warnings.warn(
No changes detected
root@8d0fa925e23a:/code/django/cantusdb_project# python manage.py migrate
 Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution
```

If you visit [staging](http://206.12.88.113/), you can see a similar error message displayed.

**Comment by jacobdgm** [comment]
Update: The app on staging is back up! It appears that the issue was related to docker: in our `docker-compose.yml` file, we had specified `postgres:alpine`, which was the postgres v14 image when we last built the container, but changed on dockerhub since then to postgres v15. The database, built in v14, was not compatible with v15 which the container was trying to run. Substituting `postgres:14-alpine` seems to do the trick.

**Comment by jacobdgm** [comment]
with #549, our Docker configuration should be all set up. These changes are now live on staging, the site is running and several pages are working as expected, and all tests are passing, so I think we're ready for testing to resume.

**Comment by jacobdgm** [comment]
welp, just found #614. Going to have to fix it before we merge this PR.

**Comment by jacobdgm** [comment]
Testing has paused again - in order to fix #614, we need to clear up whatever's going on with #607. It looks like part of the solution to #607 will involve tweaking the urls of a bunch of our views, which means we'll need to go back and test all these views again once we merge the fixes for these issues.

**Comment by dchiller** [comment]
@jacobdgm @lucasmarchd01 So just to clarify, the request is to poke around the staging site, which is still at 206.12.88.113?

**Comment by jacobdgm** [comment]
@dchiller - in general, that's still the request. A bunch of new changes went up on staging late last week, though, and I'd still like to update the list of changes in the first comment, in case people want to do focussed/directed poking rather than freeform poking.

**Comment by jacobdgm** [comment]
The list is updated! Let directed poking, as it were, commence!

**Comment by dchiller** [comment]
> * tweak logic so that if an operation is not specified in the URL query parameters, we default to a fast `startswith` search

I'm curious about this point in the Chant Search changes. When I navigate to the chant search page, the default operation is `contains` so then when I make any search without changing that default, the `op` parameter is contains. Maybe there is something else going on behind the scenes, but at least from the url it looks like the default is still contains rather than startswith.

**Comment by jacobdgm** [comment]
I've made one full pass through, with Safari. Going to merge, so that everyone in the lab can start testing on Production

**Comment by jacobdgm** [comment]
All tests are passing, and pages are loading!

**Comment by jacobdgm** [comment]
> > * tweak logic so that if an operation is not specified in the URL query parameters, we default to a fast `startswith` search
> 
> I'm curious about this point in the Chant Search changes. When I navigate to the chant search page, the default operation is `contains` so then when I make any search without changing that default, the `op` parameter is contains. Maybe there is something else going on behind the scenes, but at least from the url it looks like the default is still contains rather than startswith.

This is a fair point. What I meant to say is that if no query parameter is specified, then under the hood, we're treating it the same as if `op=starts_with`.

**Pull request merged**
